### ISSUE TITLE
Test current Vagrant VM

### ISSUE THREAD

**Issue by lukebaker** [open-review-toolkit/open-review-toolkit#9] opened 2016-09-15 20:39 UTC
@msalganik I'd like you to test out the current Vagrant setup. Once you clone this repo, you should be able to run the following commands:

``` bash
$ vagrant up
$ vagrant ssh
# Now inside Vagrant VM
$ make book
$ make site
```

With the new Vagrant setup, the `vagrant up` command will download a Vagrant box that is already customized for Open Review Toolkit. The download may be a bit longer to download the box (~1.5 GB), but there's a very quick and simple provision process (instead of a long one that could be somewhat brittle).

The `make book` command should build the PDF. You should see the PDF in the output/ directory as usual. The `make site` will build the site. You should be able to view the site via http://0.0.0.0:17278/. (In the unlikely case that there's a port collision, Vagrant may choose a port other than `17278`. I don't expect that'll happen very often, but that occurrence will be noted in the output from `vagrant up`.)

You might notice the lack of `cd` command above. Since that's what someone will need to do just about every time they ssh into the VM, I updated the vagrant user's settings to automatically change to the proper directory.

I think we're in a pretty good spot with this repo. I suspect what remains is mostly documentation and the primary site itself.

**Comment by msalganik** [comment] 2016-09-16 15:06
@lukebaker OK, I'm looking forward to trying this.  

Just one question, is there any way that this will interfere/mess-up our other vagrant process (the one we are using for my book)?

**Comment by lukebaker** [comment] 2016-09-16 15:08
> Just one question, is there any way that this will interfere/mess-up our other vagrant process (the one we are using for my book)?

No, it should create a new VM that is completely separate from your book's VM.

**Comment by msalganik** [comment] 2016-10-17 15:12
@lukebaker 

OK, I tried to get this started on my machine and I ran into a few errors.
1) your instructions skip the step "vagrant init" which has to be first (before vagrant up)
2) I solved problem (1) but then I ran into a problem when I ran "vagrant up".  Error message: "Couldn't open file /Users/mjs3/Dropbox/open-review-toolkit/base"

The full session is below.  I hope that helps.

---

mjs3@soc-macl001:~/Dropbox/open-review-toolkit$ git clone https://github.com/op
en-review-toolkit/open-review-toolkit.git
Cloning into 'open-review-toolkit'...
remote: Counting objects: 253, done.
remote: Total 253 (delta 0), reused 0 (delta 0), pack-reused 253
Receiving objects: 100% (253/253), 1.21 MiB | 0 bytes/s, done.
Resolving deltas: 100% (95/95), done.
Checking connectivity... done.
mjs3@soc-macl001:~/Dropbox/open-review-toolkit$ vagrant up
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.
mjs3@soc-macl001:~/Dropbox/open-review-toolkit$ vagrant init
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
mjs3@soc-macl001:~/Dropbox/open-review-toolkit$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'base' (v0) for provider: virtualbox
    default: Downloading: base
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/mjs3/Dropbox/open-review-toolkit/base

**Comment by lukebaker** [comment] 2016-10-17 19:38
@msalganik after your clone, you should run `cd open-review-toolkit`. Once you do that, `vagrant up` should work.

`vagrant init` is not needed, but it claimed it was needed because you weren't inside the project's directory. Once you're in that directory, vagrant will find the Vagrantfile that's inside that repo. Does that make sense?

**Comment by msalganik** [comment] 2016-10-17 21:29
Great.  Fixed.  Sorry about that.

**Comment by msalganik** [comment] 2016-10-17 21:30
When we write up the documentation for the wiki, let's make it clear that "vagrant up" will take about 5 minutes.

**Comment by msalganik** [comment] 2016-10-17 22:41
OK, this all looks great.  I've made the book and website.  Everything seems to be working perfectly.

I've made a few commits to change the text.  I hope that this helps address problems that I think other authors might encounter.

If you agree, I'm fine with closing this issue.

**Comment by msalganik** [comment] 2016-11-03 18:35
@lukebaker I think issue is ready to close.  If you agree, please close it.

**Closed as completed** 2016-11-03 18:37 UTC
